# Generated by Django 4.2.7 on 2023-11-22 22:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rate',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2, validators=[django.core.validators.MinValueValidator(0.0, message='Rate from 0 to 5.'), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
